Removed request dependency
WesVleuten/Servant pull request #10
Opened 2020-05-31 15:39 UTC by notfooddev

Replaced request dependency with node-fetch. I also noticed no oauthtoken was required for the request, which is a requirement according to the Twitch API, so I added it to the config.

This change has not been tested yet.

2020-05-31 16:14 UTC, WesVleuten requested changes
- Mixed indents
- I think we should be using an application token instead of an arbitrary auth token
- `then` -> `await`

2020-05-31 16:14 UTC, WesVleuten commented on src/events/presenceUpdate.ts
> +        .then(res => res.json())
Mixed indents

2020-06-04 21:46 UTC, notfooddev commented
![image](https://user-images.githubusercontent.com/66053378/83813397-89d9bf00-a6bd-11ea-9e45-209f6f5584d0.png)

2020-06-04 22:16 UTC, WesVleuten requested changes
Looking good, some small points of possible improvement.

Also, we should move the twitch function to a more generalized library. This could also be done at a later time, your choice.

2020-06-04 22:16 UTC, WesVleuten commented on config.example.json
> +		"accessToken": ""
Not a fan of using an arbitrary accessToken. We can use Twitch's App access tokens to fully automate the tokens.

[App access tokens](https://dev.twitch.tv/docs/authentication#types-of-tokens)
[OAuth Client Credentials Flow](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-client-credentials-flow)

2020-06-04 22:16 UTC, WesVleuten commented on src/events/presenceUpdate.ts
> +		.then(res => res.json())
Awaits > Thens

My guess:
```
const request = await fetch(...);
const data = await request.json();
```

2020-06-04 22:16 UTC, WesVleuten commented on src/events/presenceUpdate.ts
> +
Weird left in indents

2020-06-05 20:25 UTC, WesVleuten approved these changes

2020-06-05 20:26 UTC, merged